project_id = "daasmofuhleyhcnzomob"

[functions.mapbox-destinations]
verify_jwt = true

[functions.mapbox-token]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.send-confirmation-email]
verify_jwt = false