workflows:
  ios-capacitor-workflow:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Fitpas
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fitpas.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20.18.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS platform
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
          # Fix for "undefined method map for nil" error on M1 Macs
          sudo gem install ffi
          gem install xcodeproj --user-install
          cd ios/App
          # Remove old Pods and reinstall
          rm -rf Pods
          rm -rf Podfile.lock
          pod install --repo-update
          cd ../..
          npx cap sync ios
      - name: Set build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "6753996672")
          if [ -z "$LATEST_BUILD_NUMBER" ]; then
            UPDATED_BUILD_NUMBER=1
          else
            UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          fi
          cd ios/App
          agvtool new-version -all $UPDATED_BUILD_NUMBER
          echo "Build number set to: $UPDATED_BUILD_NUMBER"
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
