// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daasmofuhleyhcnzomob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhYXNtb2Z1aGxleWhjbnpvbW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzQ4MjUsImV4cCI6MjA3MzAxMDgyNX0.JXn9UFKF1LcLx_jw4sZ0H26MfhpsK3NQ0fVYltGLYt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});